[package]
name = "ordinal_system"
version = "0.1.0"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "kernel"
path = "src/kernel.rs"
bench = false
test = false