[package]
name = "ordinal_system"
version = "0.1.0"

[dependencies]
"x86_64" = "0.14.10"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
crate-type = ["staticlib"]
path="src/kernel.rs"